[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'
hook_add = '''
source ~/.vim/plugins/coc_rc.vim
'''

[[plugins]]
repo = 'RRethy/vim-illuminate'
lua_add = '''
require('illuminate').configure({
  delay = 300,
})
'''

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'tiagovla/scope.nvim'
lua_add = '''
require("scope").setup()
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
source ~/dotfiles/.vim/plugins/lualine_rc.vim
'''

[[plugins]]
repo = 'akinsho/bufferline.nvim'
tag = "v3.*"
hook_add = '''
source ~/.vim/plugins/bufferline_rc.vim
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
