[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
nnoremap <silent><Leader>qr <cmd>QuickRun<CR>
'''
hook_source = '''
source ~/.vim/plugins/quickrun_rc.vim
'''

[[plugins]]
repo = 'tiagovla/scope.nvim'
on_event = ['CmdlineEnter', 'BufRead']
lua_source = '''
require("scope").setup()
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'
on_ft = ['c', 'cpp', 'python']
on_event = 'InsertEnter'
hook_source = '''
source ~/.vim/plugins/coc_rc.vim
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = 'help'

[[plugins]]
repo = 'kylechui/nvim-surround'
on_map = {n = ['ys', 'ds', 'cs'], x = ['<Leader>s']}
lua_source = '''
require('nvim-surround').setup {
  keymaps = {
    visual =  "<Leader>s",
  },
}
'''

[[plugins]]
repo = 'numToStr/Comment.nvim'
on_map = {nx = ['gc', 'gb']}
lua_source = '''
require('Comment').setup()
'''

[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_source = 'nvim-hlslens'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
on_map = {n = ['/', '?', '#', '*', 'g#', 'g*']}
hook_source = '''
source ~/.vim/plugins/hlslens_rc.vim
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = 'BufRead'
hook_source = '''
nnoremap <Leader>gd <Cmd>Gitsigns diffthis<CR>
nnoremap <Leader>gn <Cmd>Gitsigns next_hunk<CR>
nnoremap <Leader>gN <Cmd>Gitsigns prev_hunk<CR>
nnoremap <Leader>gp <Cmd>Gitsigns preview_hunk<CR>
nnoremap <Leader>gq <Cmd>Gitsigns setqflist<CR>
nnoremap <Leader>gr <Cmd>Gitsigns reset_hunk<CR>
lua << EOF
require('gitsigns').setup()
EOF
'''

[[plugins]]
repo = 'sindrets/diffview.nvim'
on_source = 'neogit'

[[plugins]]
repo = 'TimUntersberger/neogit'
depends = ['plenary.nvim']
on_cmd = 'Neogit'
hook_add = '''
nnoremap <silent><Leader>gg <cmd>Neogit<CR>
'''
lua_source = '''
require('neogit').setup {
  disable_commit_confirmation = true,
  integrations = {
    diffview = true,
  },
}
'''

[[plugins]]
repo = 'simeji/winresizer'
on_cmd = 'WinResizerStartResize'
hook_add = '''
nnoremap <C-e> <Cmd>WinResizerStartResize<CR>
let g:winresizer_vert_resize=1
let g:winresizer_horiz_resize=1
'''

[[plugins]]
repo = 'RRethy/vim-illuminate'
on_event = 'BufRead'
lua_source = '''
require('illuminate').configure({
  delay = 300,
})
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = ['telescope.nvim', 'neogit']

[[plugins]]
repo = 'tami5/sqlite.lua'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim']
on_lua = 'telescope'
hook_source = '''
source ~/.vim/plugins/telescope_rc.vim
'''
hook_add = '''
nnoremap <Leader>fr <Cmd>lua require('telescope').extensions.frecency.frecency()<CR>
nnoremap <Leader>fb <Cmd>lua require('telescope').extensions.file_browser.file_browser()<CR>
nnoremap <Leader>ff <Cmd>lua require('telescope.builtin').find_files()<CR>
nnoremap <Leader>fg <Cmd>lua require('telescope.builtin').live_grep()<CR>
nnoremap <Leader>b <Cmd>lua require('telescope.builtin').buffers()<CR>
nnoremap <Leader>tk <Cmd>lua require('telescope.builtin').keymaps()<CR>
nnoremap <Leader>ts <Cmd>lua require('telescope.builtin').search_history()<CR>
nnoremap <Leader>th <Cmd>lua require('telescope.builtin').command_history()<CR>
nnoremap <Leader>tc <Cmd>lua require('telescope.builtin').commands()<CR>
nnoremap <Leader>tr <Cmd>lua require('telescope.builtin').registers()<CR>
nnoremap <Leader>tm <Cmd>lua require('telescope.builtin').marks()<CR>
nnoremap <Leader>tj <Cmd>lua require('telescope.builtin').jumplist()<CR>
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
on_source = 'telescope.nvim'
build = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' 

[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'
depends = ['sqlite.lua']
on_source = 'telescope.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'kevinhwang91/nvim-bqf'
on_ft = 'qf'
lua_source = '''
require("bqf").setup {
  func_map = {
    pscrollup = '<C-u>',
    pscrolldown = '<C-d>',
    split = '<C-s>'
  },
}
'''

[[plugins]]
repo = 'haya14busa/vim-edgemotion'
on_map = '<Plug>(edgemotion-'
hook_add = '''
nnoremap <C-j> <Plug>(edgemotion-j)
nnoremap <C-k> <Plug>(edgemotion-k)
vnoremap <C-j> <Plug>(edgemotion-j)
vnoremap <C-k> <Plug>(edgemotion-k)
'''

[[plugins]]
repo = 'ggandor/leap.nvim'
on_map = {nx = ['s', 'S', 'gs']}
lua_source = '''
local leap = require('leap')
leap.add_default_mappings()
leap.opts.safe_labels =   { "s", "f", "n", "u", "t",
      "S", "F", "N", "L", "H", "M", "U", "G", "T", "Z"} 
leap.opts.labels =     { "s", "f", "n", "j", "k", "l", "h",
      "o", "d", "w", "e", "m", "b", "u", "v", "r", "g", "t",
      "c", "x", "z", "S", "F", "N", "J", "K", "L", "H", "O",
      "D", "W", "E", "M", "B", "U", "V", "R", "G", "T", "C",
      } 
'''

[[plugins]]
repo = 'phaazon/hop.nvim'
rev = 'v2'
on_lua = 'hop'
hook_add = '''
nnoremap <silent><leader>hl <Cmd>lua require('hop').hint_lines_skip_whitespace()<CR>
nnoremap <silent><leader>hc <Cmd>lua require('hop').hint_char1()<CR>
nnoremap <silent><leader>hw <Cmd>lua require('hop').hint_words()<CR>
xnoremap <silent><leader>hl <Cmd>lua require('hop').hint_lines_skip_whitespace()<CR>
xnoremap <silent><leader>hc <Cmd>lua require('hop').hint_char1()<CR>
xnoremap <silent><leader>hw <Cmd>lua require('hop').hint_words()<CR>
'''
lua_source = '''
require('hop').setup()
'''

[[plugins]]
repo = 'gabrielpoca/replacer.nvim'
on_ft = 'qf'
hook_add = '''
nnoremap <silent><leader>rp <Cmd>lua require("replacer").run({rename_files = false})<CR>
'''

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
lua_source = '''
require("nvim-autopairs").setup {
  map_c_h = true,
  map_c_w = true,
}
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
on_map = '<Plug>(fern-action-'
hook_source = '''
source ~/.vim/plugins/fern_rc.vim
'''

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
depends = ['gitsigns.nvim']
on_cmd = 'ScrollbarShow'
lua_source = '''
require("scrollbar").setup {
  handle = { color = '#384863' },
  marks = {
    Search = { color = '#ffffff'},
    GitAdd = { color = '#41bdbf' },
    GitChange = { color = '#c9c542'},
    GitDelete = { color = '#bd3c56'},
  },
  handlers = {
    cursor = false,
    gitsigns = true,
  },
}
'''

[[plugins]]
repo = 'nvim-tree/nvim-tree.lua'
on_cmd = ['NvimTreeOpen', 'NvimTreeFocus', 'NvimTreeFindFile']
hook_add = '''
nnoremap <silent><leader>nn <Cmd>NvimTreeFocus<CR>
nnoremap <silent><leader>nf <Cmd>NvimTreeFindFile<CR>
nnoremap <silent><leader>nq <Cmd>NvimTreeClose<CR>
nmap <silent><leader>no <Cmd>NvimTreeOpen %:h<CR>
'''
hook_source = '''
source ~/.vim/plugins/nvimtree_rc.vim
'''

[[plugins]]
repo = 'famiu/bufdelete.nvim'
on_cmd = 'Bdelete'
hook_add = '''
nnoremap <Leader>x <cmd>Bdelete<cr>
nnoremap <Leader>X <cmd>Bdelete!<cr>
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = {nxo = '<Plug>(clever-'}
hook_add = '''
let g:clever_f_not_overwrites_standard_mappings = 1
let g:clever_f_mark_direct = 1
let g:clever_f_smart_case = 1
let g:clever_f_use_migemo = 1
nmap f <Plug>(clever-f-f)
xmap f <Plug>(clever-f-f)
omap f <Plug>(clever-f-f)
nmap F <Plug>(clever-f-F)
xmap F <Plug>(clever-f-F)
omap F <Plug>(clever-f-F)
nmap t <Plug>(clever-f-t)
xmap t <Plug>(clever-f-t)
omap t <Plug>(clever-f-t)
nmap T <Plug>(clever-f-T)
xmap T <Plug>(clever-f-T)
omap T <Plug>(clever-f-T)
map <CR> <Plug>(clever-f-repeat-forward)
map <BS> <Plug>(clever-f-repeat-back)
map <C-n> <Plug>(clever-f-repeat-back)
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_cmd = 'ColorizerAttachToBuffer'
lua_source = '''
require'colorizer'.setup()
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
lua_source = '''
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {'latex', 'help'},
  },
  indent = {
    enable = true,
    disable = {'python'},
  },
  ensure_installed = 'all',
}
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'andymass/vim-matchup'
on_source = 'nvim-treesitter'
hook_add = '''
nnoremap <C-p> <Plug>(matchup-%)
'''

[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'CmdwinEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

[[plugins]]
repo = 'karb94/neoscroll.nvim'
on_map = {nx = ['<C-u>', '<C-d>']}
lua_source = '''
require('neoscroll').setup {
  mappings = {},
}
local t = {}
t['<C-u>'] = {'scroll', {'-vim.wo.scroll', 'true', '100'}}
t['<C-d>'] = {'scroll', {'vim.wo.scroll', 'true', '100'}}
t['zt'] = {'zt', {'100'}}
t['zz'] = {'zz', {'100'}}
t['zb'] = {'zb', {'100'}}
require('neoscroll.config').set_mappings(t)
'''

[[plugins]]
repo = 'chentoast/marks.nvim'
on_cmd = 'MarksToggleSigns'
lua_source = '''
require'marks'.setup{
  mappings = {
    next = ']m',
    prev = '[m',
  },
}
'''
hook_add = '''
nnoremap <silent><Leader>mt <Cmd>MarksToggleSigns<CR>
nnoremap <silent><Leader>mb <Cmd>MarksListBuf<CR>
nnoremap <silent><Leader>ma <Cmd>MarksListAll<CR>
nnoremap <silent><Leader>mg <Cmd>MarksListGlobal<CR>
'''

[[plugins]]
repo = 'tpope/vim-abolish'
on_cmd = 'Subvert'

[[plugins]]
repo = 'kana/vim-textobj-user'
on_source = 'vim-textobj-entire'

[[plugins]]
repo = 'kana/vim-textobj-entire'
on_map = {n = ['c', 'd', 'v']}

[[plugins]]
repo = 'wellle/targets.vim'
on_source = 'vim-textobj-entire'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'
on_source = 'noice.nvim'

[[plugins]]
repo = 'folke/noice.nvim'
on_event = 'CmdlineEnter'
hook_source = '''
source ~/.vim/plugins/noice_rc.vim
'''

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_ft = ['html', 'xml', 'javascript', 'javascriptreact', 'typescript', 'typescriptreact']
lua_source = '''
require('nvim-ts-autotag').setup()
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
hook_source = '''
autocmd FileType python setlocal indentexpr=GetPythonPEPIndent(v:lnum)
'''
