[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
nnoremap <silent><Leader>r <cmd>QuickRun<CR>
'''
hook_source = '''
source ~/.vim/plugins/quickrun_rc.vim
'''

[[plugins]]
repo = 'simeji/winresizer'
on_cmd = 'WinResizerStartResize'
hook_add = '''
nnoremap <C-e> <cmd>WinResizerStartResize<CR>
'''

[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'
depends = ['sqlite.lua']
on_cmd = 'Telescope frecency'
hook_add = '''
nnoremap <Leader>fr <cmd>Telescope frecency<CR>
lua << EOF
require('telescope').load_extension('frecency')
EOF
'''

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
on_cmd = 'Telescope file_browser'
hook_add = '''
nnoremap <Leader>fb <cmd>Telescope file_browser<CR>
lua << EOF
require('telescope').load_extension('file_browser')
EOF
'''

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
lua_source = '''
require("nvim-autopairs").setup()
'''

[[plugins]]
repo = 'sindrets/diffview.nvim'
on_cmd = ['DiffviewOpen', 'DiffviewFileHistory']

[[plugins]]
repo = 'lambdalisue/fern.vim'
on_map = '<Plug>(fern-action-'
hook_source = '''
source ~/.vim/plugins/fern_rc.vim
'''

[[plugins]]
repo = 'nvim-tree/nvim-tree.lua'
on_cmd = ['NvimTreeOpen', 'NvimTreeFocus', 'NvimTreeFindFile']
hook_add = '''
nnoremap <leader>nn <cmd>NvimTreeFocus<CR>
nnoremap <leader>nf <cmd>NvimTreeFindFile<CR>
nnoremap <leader>nq <cmd>NvimTreeClose<CR>
'''
hook_source = '''
source ~/.vim/plugins/nvimtree_rc.vim
'''

[[plugins]]
repo = 'famiu/bufdelete.nvim'
on_cmd = 'Bdelete'
hook_add = '''
nnoremap <Leader>x <cmd>Bdelete<cr>
nnoremap <Leader>X <cmd>Bdelete!<cr>
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = {nxo = '<Plug>'}
hook_add = '''
let g:clever_f_not_overwrites_standard_mappings = 1
let g:clever_f_mark_direct = 1
let g:clever_f_smart_case = 1
let g:clever_f_use_migemo = 1
nmap f <Plug>(clever-f-f)
xmap f <Plug>(clever-f-f)
omap f <Plug>(clever-f-f)
nmap F <Plug>(clever-f-F)
xmap F <Plug>(clever-f-F)
omap F <Plug>(clever-f-F)
nmap t <Plug>(clever-f-t)
xmap t <Plug>(clever-f-t)
omap t <Plug>(clever-f-t)
nmap T <Plug>(clever-f-T)
xmap T <Plug>(clever-f-T)
omap T <Plug>(clever-f-T)
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_cmd = 'ColorizerAttachToBuffer'
lua_source = '''
require'colorizer'.setup()
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
lua_source = '''
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {'latex', 'help'},
  },
  refactor = {
    highlight_defintions = {
      enable = true,
    },
    smart_rename = {
      enable = true,
      smart_rename = 'grr'
    },
    navigation = {
      enable = true,
      goto_definition = 'gnd',
      list_definitions = 'gnD',
    },
  },
  ignore_install = { "phpdoc", "help" },
  ensure_installed = 'all',
}
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'CmdwinEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

