[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'
hook_add = '''
source ~/.vim/plugins/coc_rc.vim
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim']
hook_add = '''
source ~/.vim/plugins/telescope_rc.vim
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' 
lua_add = '''
require('telescope').load_extension('fzf')
'''

[[plugins]]
repo = 'tami5/sqlite.lua'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
lua_add = '''
require('gitsigns').setup()
'''

[[plugins]]
repo = 'RRethy/vim-illuminate'
lua_add = '''
require('illuminate').configure({
  delay = 300,
})
'''

[[plugins]]
repo = 'ggandor/leap.nvim'
lua_add = '''
require('leap').add_default_mappings()
'''

[[plugins]]
repo = 'kylechui/nvim-surround'
lua_add = '''
require('nvim-surround').setup()
'''

[[plugins]]
repo = 'phaazon/hop.nvim'
rev = 'v2'
hook_add = '''
nnoremap <silent><leader>hw :<C-u>HopWord<CR>
nnoremap <silent><leader>hl :<C-u>HopLineStart<CR>
nnoremap <silent><leader>hc :<C-u>HopChar1<CR>
vnoremap <silent><leader>hw :<C-u>HopWord<CR>
vnoremap <silent><leader>hl :<C-u>HopLineStart<CR>
vnoremap <silent><leader>hc :<C-u>HopChar1<CR>
'''
lua_add = '''
require('hop').setup()
'''

[[plugins]]
repo = 'numToStr/Comment.nvim'
lua_add = '''
require('Comment').setup()
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
lua_add = '''
require('indent_blankline').setup()
'''

[[plugins]]
repo = 'tiagovla/scope.nvim'
lua_add = '''
require("scope").setup()
'''

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
lua_add = '''
require('hlslens').setup {
  calm_down = true,
  nearest_only = true,
}

local kopts = {noremap = true, silent = true}

vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', 'N',
    [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
vim.api.nvim_set_keymap('n', '*', [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', '#', [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
vim.api.nvim_set_keymap('n', 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)

vim.api.nvim_set_keymap('n', '<Leader>l', ':noh<CR>', kopts)
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
source ~/dotfiles/.vim/plugins/lualine_rc.vim
'''

[[plugins]]
repo = 'akinsho/bufferline.nvim'
tag = "v3.*"
hook_add = '''
source ~/.vim/plugins/bufferline_rc.vim
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tpope/vim-fugitive'

