[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
nnoremap <silent><Leader>q <cmd>QuickRun<CR>
'''
hook_source = '''
source ~/.vim/plugins/quickrun_rc.vim
'''

[[plugins]]
repo = 'sindrets/diffview.nvim'
on_source = 'neogit'

[[plugins]]
repo = 'TimUntersberger/neogit'
on_cmd = 'Neogit'
hook_add = '''
nnoremap <silent><Leader>g <cmd>Neogit<CR>
'''
lua_source = '''
require('neogit').setup {
  integrations = {
    diffview = true,
  },
}
'''

[[plugins]]
repo = 'simeji/winresizer'
on_cmd = 'WinResizerStartResize'
hook_add = '''
nnoremap <C-e> <cmd>WinResizerStartResize<CR>
let g:winresizer_vert_resize=1
let g:winresizer_horiz_resize=1
'''

[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'
depends = ['sqlite.lua']
on_cmd = 'Telescope frecency'
hook_add = '''
nnoremap <Leader>fr <cmd>Telescope frecency<CR>
lua << EOF
require('telescope').load_extension('frecency')
EOF
'''

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
on_cmd = 'Telescope file_browser'
hook_add = '''
nnoremap <Leader>fb <cmd>Telescope file_browser<CR>
lua << EOF
require('telescope').load_extension('file_browser')
EOF
'''

[[plugins]]
repo = 'kevinhwang91/nvim-bqf'
on_ft = 'qf'
lua_source = '''
require("bqf").setup {
  func_map = {
    pscrollup = '<C-u>',
    pscrolldown = '<C-d>',
  },
}
'''

[[plugins]]
repo = 'haya14busa/vim-edgemotion'
on_map = '<Plug>(edgemotion-'
hook_add = '''
nnoremap <C-j> <Plug>(edgemotion-j)
nnoremap <C-k> <Plug>(edgemotion-k)
vnoremap <C-j> <Plug>(edgemotion-j)
vnoremap <c-k> <plug>(edgemotion-k)
'''

[[plugins]]
repo = 'gabrielpoca/replacer.nvim'
on_ft = 'qf'
hook_add = '''
nnoremap <silent><leader>rp :<C-u>lua require("replacer").run()<cr>
'''

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'InsertEnter'
lua_source = '''
require("nvim-autopairs").setup()
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
on_map = '<Plug>(fern-action-'
hook_source = '''
source ~/.vim/plugins/fern_rc.vim
'''

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
depends = ['nvim-hlslens', 'gitsigns.nvim']
on_event = 'BufRead'
lua_source = '''
require("scrollbar").setup {
  handle = { color = '#384863' },
  marks = {
    Search = { color = '#ffffff'},
    GitAdd = { color = '#41bdbf' },
    GitChange = { color = '#c9c542'},
    GitDelete = { color = '#bd3c56'},
  },
  handlers = {
    cursor = false,
    gitsigns = true,
  },
}
'''

[[plugins]]
repo = 'nvim-tree/nvim-tree.lua'
on_cmd = ['NvimTreeOpen', 'NvimTreeFocus', 'NvimTreeFindFile']
hook_add = '''
nnoremap <leader>nn <cmd>NvimTreeFocus<CR>
nnoremap <leader>nf <cmd>NvimTreeFindFile<CR>
nnoremap <leader>nq <cmd>NvimTreeClose<CR>
'''
hook_source = '''
source ~/.vim/plugins/nvimtree_rc.vim
'''

[[plugins]]
repo = 'famiu/bufdelete.nvim'
on_cmd = 'Bdelete'
hook_add = '''
nnoremap <Leader>x <cmd>Bdelete<cr>
nnoremap <Leader>X <cmd>Bdelete!<cr>
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = {nxo = '<Plug>'}
hook_add = '''
let g:clever_f_not_overwrites_standard_mappings = 1
let g:clever_f_mark_direct = 1
let g:clever_f_smart_case = 1
let g:clever_f_use_migemo = 1
nmap f <Plug>(clever-f-f)
xmap f <Plug>(clever-f-f)
omap f <Plug>(clever-f-f)
nmap F <Plug>(clever-f-F)
xmap F <Plug>(clever-f-F)
omap F <Plug>(clever-f-F)
nmap t <Plug>(clever-f-t)
xmap t <Plug>(clever-f-t)
omap t <Plug>(clever-f-t)
nmap T <Plug>(clever-f-T)
xmap T <Plug>(clever-f-T)
omap T <Plug>(clever-f-T)
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_cmd = 'ColorizerAttachToBuffer'
lua_source = '''
require'colorizer'.setup()
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
lua_source = '''
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {'latex', 'help'},
  },
  refactor = {
    highlight_defintions = {
      enable = true,
    },
    smart_rename = {
      enable = true,
      smart_rename = 'grr'
    },
    navigation = {
      enable = true,
      goto_definition = 'gnd',
      list_definitions = 'gnD',
    },
  },
  ignore_install = { "phpdoc", "help" },
  ensure_installed = 'all',
  matchup = {
    enable = true,
    disable_virtual_text = true,
  },
}
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'andymass/vim-matchup'
on_source = 'nvim-treesitter'
hook_add = '''
inoremap <C-p> <ESC><Plug>(matchup-%)
nnoremap <C-p> <Plug>(matchup-%)
'''

[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'CmdwinEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

