[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'
hook_add = '''
source ~/.vim/plugins/coc_rc.vim
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
source ~/.vim/plugins/telescope_rc.vim
'''

[[plugins]]
repo = 'tami5/sqlite.lua'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'
hook_add = '''
nnoremap <C-f> <cmd>Telescope frecency<cr>
lua << EOF
require"telescope".load_extension("frecency")
EOF
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
lua_add = '''
require('gitsigns').setup()
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
lua_add = '''
require('indent_blankline').setup()
'''

[[plugins]]
repo = 'numToStr/Comment.nvim'
lua_add = '''
require('Comment').setup()
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
source ~/dotfiles/.vim/plugins/lualine.vim
'''

[[plugins]]
repo = 'akinsho/bufferline.nvim'
tag = "v3.*"
hook_add = '''
source ~/.vim/plugins/bufferline_rc.vim
'''

[[plugins]]
repo = 'tiagovla/scope.nvim'
lua_add = '''
require("scope").setup()
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tpope/vim-fugitive'

