[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
source ~/dotfiles/.vim/plugins/lualine_rc.vim
'''

[[plugins]]
repo = 'akinsho/bufferline.nvim'
tag = "v3.*"
hook_add = '''
source ~/.vim/plugins/bufferline_rc.vim
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
lua_add = '''
require('indent_blankline').setup()
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'
